server:
  port: ${SERVER_PORT:8081}

app:
  api-gateway-url: http://localhost:8000

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/user_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration

# Service discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
  instance:
    prefer-ip-address: true

# Logging
logging:
  level:
    root: INFO
    com.example.user_service: DEBUG

    org.hibernate: DEBUG
    org.springframework.orm.jpa: DEBUG

jwt:
  secret: "21808c7f2c761f078358d8589dff41d75078e8130e1c18c0760c70db29b6ab94"
  expiration: 3600000
  refresh-expiration: 604800000
